// Use native Unicode emoji in message content. Custom emoji IDs can belong to
// another server and Discord renders them as :name: when they are unavailable.
// Native emoji work in every guild and keep setup/error messages readable.
const NATIVE = {
  axex_creation: "🗓️",
  axex_owner: "👑",
  axex_bot: "🤖",
  axex_protected: "🛡️",
  axex_reminder: "💡",
  axex_scan: "🔎",
  axex_captcha: "🧩",
  axex_server: "🏠",
  axex_quarantine: "🚫",
  axex_help: "❔",
  axex_failed: "❌",
  axex_cooldown: "⏳",
  axex_arrow: "➜",
  axex_user: "👤",
  axex_loading: "🔄",
  axex_link: "🔗",
  axex_new_account: "🆕",
  axex_logs: "📋",
  axex_kick: "👢",
  axex_honeypot: "🍯",
  axex_channel: "📁",
  axex_ban: "🔨",
  axex_invisible: "👻",
  axex_warning: "⚠️",
  axex_success: "✅",
  axex_anti_raid: "🚨",
  axex_anti_nuke: "💥",
  axex_id_card: "🪪",
  axex_webhook: "🔌",
  axex_vpn: "🌐",
  axex_timeout: "⌛",
  axex_role: "🎭",
};

const emoji = (name) => NATIVE[name] || "•";

const E = {
  creation: emoji("axex_creation"),
  owner: emoji("axex_owner"),
  bot: emoji("axex_bot"),
  protected: emoji("axex_protected"),
  reminder: emoji("axex_reminder"),
  scan: emoji("axex_scan"),
  captcha: emoji("axex_captcha"),
  server: emoji("axex_server"),
  quarantine: emoji("axex_quarantine"),
  help: emoji("axex_help"),
  failed: emoji("axex_failed"),
  cooldown: emoji("axex_cooldown"),
  arrow: emoji("axex_arrow"),
  user: emoji("axex_user"),
  loading: emoji("axex_loading"),
  link: emoji("axex_link"),
  newAccount: emoji("axex_new_account"),
  logs: emoji("axex_logs"),
  kick: emoji("axex_kick"),
  honeypot: emoji("axex_honeypot"),
  channel: emoji("axex_channel"),
  ban: emoji("axex_ban"),
  invisible: emoji("axex_invisible"),
  warning: emoji("axex_warning"),
  success: emoji("axex_success"),
  antiRaid: emoji("axex_anti_raid"),
  antiNuke: emoji("axex_anti_nuke"),
  idCard: emoji("axex_id_card"),
  webhook: emoji("axex_webhook"),
  vpn: emoji("axex_vpn"),
  timeout: emoji("axex_timeout"),
  role: emoji("axex_role"),
};

// Compatibility aliases used by existing verification and message modules.
Object.assign(E, {
  memberjoined: E.user,
  id: E.idCard,
  error: E.warning,
  pending: E.cooldown,
  verify: E.captcha,
  unverified: E.quarantine,
  suspicious: E.scan,
  unsuccessful: E.failed,
  verified: E.success,
});

E.fallback = {
  creation: "🗓️",
  owner: "👑",
  bot: "🤖",
  protected: "🛡️",
  reminder: "💡",
  scan: "🔎",
  captcha: "🧩",
  server: "🏠",
  quarantine: "🚫",
  help: "❔",
  failed: "❌",
  cooldown: "⏳",
  arrow: "➜",
  user: "👤",
  loading: "🔄",
  link: "🔗",
  warning: "⚠️",
  success: "✅",
  timeout: "⌛",
  role: "🎭",
  vpn: "🌐",
  logs: "📋",
  antiRaid: "🚨",
  antiNuke: "💥",
};

module.exports = E;
